### ISSUE TITLE
記事の作成や編集において，一部の入力を自動化する．

### ISSUE THREAD

**Issue by murata1224** [nomlab/nomnichi-haskell#19]
作成における不要な入力は，
・MemberName
・Count
自動化する入力は，
・PremaLink

編集における不要な入力は，
・PermaLink
・MemberName
・Count

**Comment by kobayashi1027** [comment]
10月中旬までに，チームO（檀上，岡田，小林，中村）で実装する．

**Comment by oppapili** [comment]
現在，articleはmemberNameとしてTextをもっている．
しかし，ここはmemberId Intを持つのがよい．
このため，ArticleのもつmemberNameをmemberIdに変更する．
また，既存のDBのArticleに対してmigrationをかける必要があるが，
Yesodのmigrationはあまり賢くないので，この手法について検討が必要である．

**Comment by oppapili** [comment]
issue 解決のためのTODOは以下の3つである．
- maybeAuthId の型をフォームにあうようにうまく調整する方法を見つける
- Article の memberName カラム を利用している箇所を洗い出し， DB から id を使って取得するよう変更
- memberName -> memberId にマイグレーションするのに，不整合が起きないか，起きたときにどう対処すれば良いかを調査する
  1. 空のDB(変更後のカラム構成の)作成
  2. 今までのDBからスクリプトで空のDBに値を埋める

**Comment by murata1224** [comment]
完了したためcloseする．
