### ISSUE TITLE
ノムニチ記事で誤って記事を消してしまうので削除手順を見直してほしい

### ISSUE THREAD

**Issue by nakao4532** [nomlab/nomnichi-haskell#38]
ノムニチの記事で削除ボタンを押すとすぐに削除されてしまうため，確認ページを表示するか削除ボタンの場所を変更して欲しい．

**Comment by oppapili** [comment]
#47 の中で記事削除の際に confirm するようにした．
削除手順を見直したので，本 issue を close する．
